#!/bin/sh
# NetworkManager runs this whenever a connection goes up or down.
# When the RPIZERO-OPEN hotspot comes up, flash the power light; when it goes down, put it back.
# Installed to /etc/NetworkManager/dispatcher.d/ by RPiZero Task Manager.
[ "$CONNECTION_ID" = "RPIZERO-OPEN" ] || exit 0
case "$2" in
    up)             /usr/local/bin/rpizero-helper led start ;;
    down|pre-down)  /usr/local/bin/rpizero-helper led stop ;;
esac
exit 0
